# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish Server Resources

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    environment: ServerCodeBuild
    steps:
    - uses: actions/checkout@v4
   
    - name: (GLOBAL) Extract version number
      id: extract_version
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          VERSION=$(echo "${{ github.event.pull_request.title }}" | grep -oP '^[a-zA-z\-]*\d+\.\d+\.\d+')
        else
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '^[a-zA-z\-]*\d+\.\d+\.\d+')
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: (SERVER) Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: (SERVER) Restore dependencies
      run: dotnet restore
    
    - name: (SERVER) Install Entity Framework
      run: |
           dotnet tool install --global dotnet-ef
           dotnet tool restore
    
    - name: (SERVER) Scaffold Prod-Game Database    
      if: ${{ ! startsWith(steps.extract_version.outputs.version, 'dev') }}
      working-directory: ./ChoiceVDatabaseGenerator
      env:
        DB_HOST: ${{ vars.DB_HOST }}
        DB_DATABASE: ${{ vars.DB_DATABASE }}
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: dotnet-ef dbcontext scaffold "Server=$DB_HOST;Port=3306;Database=$DB_DATABASE;Username=$DB_USERNAME;Password='$DB_PASSWORD'" Pomelo.EntityFrameworkCore.MySql --output-dir Model/Database --context ChoiceVDb --force --use-database-names --project ChoiceVDatabaseGenerator/ChoiceV.csproj 
    
    - name: (SERVER) Scaffold Dev-Game Database    
      if: ${{ startsWith(steps.extract_version.outputs.version, 'dev') }}
      working-directory: ./ChoiceVDatabaseGenerator
      env:
        DB_HOST: ${{ vars.DB_HOST }}
        DB_DEV_DATABASE: ${{ vars.DB_DEV_DATABASE }}
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: dotnet-ef dbcontext scaffold "Server=$DB_HOST;Port=3306;Database=$DB_DEV_DATABASE;Username=$DB_USERNAME;Password='$DB_PASSWORD'" Pomelo.EntityFrameworkCore.MySql --output-dir Model/Database --context ChoiceVDb --force --use-database-names --project ChoiceVDatabaseGenerator/ChoiceV.csproj 
    
    - name: (SERVER) Scaffold FileSystem Database
      working-directory: ./ChoiceVDatabaseGenerator
      env:
        DB_HOST: ${{ vars.DB_HOST }}
        DB_FS_DATABASE: ${{ vars.DB_FS_DATABASE }}
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: dotnet-ef dbcontext scaffold "Server=$DB_HOST;Port=3306;Database=$DB_FS_DATABASE;Username=$DB_USERNAME;Password='$DB_PASSWORD'" Pomelo.EntityFrameworkCore.MySql --output-dir Model/FsDatabase --context ChoiceVFsDb --force --use-database-names --project ChoiceVDatabaseGenerator/ChoiceV.csproj 
   
    - name: (SERVER) Replace Connection String and build (copy to code)
      working-directory: ./ChoiceVDatabaseGenerator
      run: | 
        ./script.bash; 
        dotnet build
    
    - name: (SERVER) Build the Gameserver
      run: dotnet build --configuration Release --no-restore -o ./build/resources/ChoiceVServer
    
    - name: (CLIENT) Copy the Clientside
      run: cp -r ./server/resources/ChoiceVClient ./build/resources/ChoiceVClient

    - name: (CEF) Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: 'ChoiceVCef/choicev-cef/package-lock.json'
        
    - name: (CEF) Run Node Builds
      working-directory: 'ChoiceVCef/choicev-cef'
      env: 
        BUILD_PATH: "./../../build/ChoiceVCEF"
        CI: false
      run:  |
        npm ci
        npm run build

    - name: (GLOBAL) Pushes to ChoiceVBuilds
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.BUILDS_DEPLOY_KEY }}
      with:
        source-directory: 'build'
        destination-github-username: 'ericr98'
        destination-repository-name: 'ChoiceVBuilds'
        user-email: eric@rosche.net
        target-branch: main
        target-directory: server/${{ steps.extract_version.outputs.version }}

